name: CI

# タイミングを指定
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: npm install
        run: npm install
      - name: Eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,tsx,js,jsx}'
      - name: Run eslint
        run: npm run lint
      - name: Run Jest
        run: npm run test
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
      - name: Show coverage in comments
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "jest --coverage"
