name: CI

# タイミングを指定
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: npm install
        run: npm install
      - name: Eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,tsx,js,jsx}'
      - name: Run eslint
        run: npm run lint
      - name: Run Jest
        run: npm run test -- --coverage
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: tests
          name: codecov-umbrella
          fail_ci_if_error: true